spring:
  application:
    name: Memorify
  ai:
    ollama:
      chat:
        model: mistral
  jpa:
    show-sql: false

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    jdbc:
      dialect: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/player-db
    password: 1234
    username: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8762/realms/master
  servlet:
    multipart:
      max-file-size: 50MB

application:
  file:
    uploads:
      media-output-path: ./uploads

server:
  port: 8080
springdoc:
   default-produces-media-type: application/json