/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessageRequest model module.
 * @module model/MessageRequest
 * @version v0
 */
class MessageRequest {
    /**
     * Constructs a new <code>MessageRequest</code>.
     * @alias module:model/MessageRequest
     */
    constructor() { 
        
        MessageRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessageRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageRequest} obj Optional instance to populate.
     * @return {module:model/MessageRequest} The populated <code>MessageRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageRequest();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('senderId')) {
                obj['senderId'] = ApiClient.convertToType(data['senderId'], 'String');
            }
            if (data.hasOwnProperty('receiverId')) {
                obj['receiverId'] = ApiClient.convertToType(data['receiverId'], 'String');
            }
            if (data.hasOwnProperty('messageType')) {
                obj['messageType'] = ApiClient.convertToType(data['messageType'], 'String');
            }
            if (data.hasOwnProperty('chatId')) {
                obj['chatId'] = ApiClient.convertToType(data['chatId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MessageRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MessageRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['senderId'] && !(typeof data['senderId'] === 'string' || data['senderId'] instanceof String)) {
            throw new Error("Expected the field `senderId` to be a primitive type in the JSON string but got " + data['senderId']);
        }
        // ensure the json data is a string
        if (data['receiverId'] && !(typeof data['receiverId'] === 'string' || data['receiverId'] instanceof String)) {
            throw new Error("Expected the field `receiverId` to be a primitive type in the JSON string but got " + data['receiverId']);
        }
        // ensure the json data is a string
        if (data['messageType'] && !(typeof data['messageType'] === 'string' || data['messageType'] instanceof String)) {
            throw new Error("Expected the field `messageType` to be a primitive type in the JSON string but got " + data['messageType']);
        }
        // ensure the json data is a string
        if (data['chatId'] && !(typeof data['chatId'] === 'string' || data['chatId'] instanceof String)) {
            throw new Error("Expected the field `chatId` to be a primitive type in the JSON string but got " + data['chatId']);
        }

        return true;
    }


}



/**
 * @member {String} content
 */
MessageRequest.prototype['content'] = undefined;

/**
 * @member {String} senderId
 */
MessageRequest.prototype['senderId'] = undefined;

/**
 * @member {String} receiverId
 */
MessageRequest.prototype['receiverId'] = undefined;

/**
 * @member {module:model/MessageRequest.MessageTypeEnum} messageType
 */
MessageRequest.prototype['messageType'] = undefined;

/**
 * @member {String} chatId
 */
MessageRequest.prototype['chatId'] = undefined;





/**
 * Allowed values for the <code>messageType</code> property.
 * @enum {String}
 * @readonly
 */
MessageRequest['MessageTypeEnum'] = {

    /**
     * value: "TEXT"
     * @const
     */
    "TEXT": "TEXT",

    /**
     * value: "IMAGE"
     * @const
     */
    "IMAGE": "IMAGE",

    /**
     * value: "AUDIO"
     * @const
     */
    "AUDIO": "AUDIO",

    /**
     * value: "VIDEO"
     * @const
     */
    "VIDEO": "VIDEO"
};



export default MessageRequest;

