/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WordMeaningDto model module.
 * @module model/WordMeaningDto
 * @version v0
 */
class WordMeaningDto {
    /**
     * Constructs a new <code>WordMeaningDto</code>.
     * @alias module:model/WordMeaningDto
     */
    constructor() { 
        
        WordMeaningDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WordMeaningDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WordMeaningDto} obj Optional instance to populate.
     * @return {module:model/WordMeaningDto} The populated <code>WordMeaningDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WordMeaningDto();

            if (data.hasOwnProperty('word')) {
                obj['word'] = ApiClient.convertToType(data['word'], 'String');
            }
            if (data.hasOwnProperty('meaning')) {
                obj['meaning'] = ApiClient.convertToType(data['meaning'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WordMeaningDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WordMeaningDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['word'] && !(typeof data['word'] === 'string' || data['word'] instanceof String)) {
            throw new Error("Expected the field `word` to be a primitive type in the JSON string but got " + data['word']);
        }
        // ensure the json data is a string
        if (data['meaning'] && !(typeof data['meaning'] === 'string' || data['meaning'] instanceof String)) {
            throw new Error("Expected the field `meaning` to be a primitive type in the JSON string but got " + data['meaning']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {String} word
 */
WordMeaningDto.prototype['word'] = undefined;

/**
 * @member {String} meaning
 */
WordMeaningDto.prototype['meaning'] = undefined;

/**
 * @member {String} type
 */
WordMeaningDto.prototype['type'] = undefined;






export default WordMeaningDto;

