/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ChatResponse from './model/ChatResponse';
import MessageRequest from './model/MessageRequest';
import MessageResponse from './model/MessageResponse';
import UploadMediaRequest from './model/UploadMediaRequest';
import UserResponse from './model/UserResponse';
import WordMeaningDto from './model/WordMeaningDto';
import ChatApi from './api/ChatApi';
import MessageApi from './api/MessageApi';
import SudokuControllerApi from './api/SudokuControllerApi';
import TicTacToeControllerApi from './api/TicTacToeControllerApi';
import UserApi from './api/UserApi';
import WordMeaningControllerApi from './api/WordMeaningControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ChatResponse model constructor.
     * @property {module:model/ChatResponse}
     */
    ChatResponse,

    /**
     * The MessageRequest model constructor.
     * @property {module:model/MessageRequest}
     */
    MessageRequest,

    /**
     * The MessageResponse model constructor.
     * @property {module:model/MessageResponse}
     */
    MessageResponse,

    /**
     * The UploadMediaRequest model constructor.
     * @property {module:model/UploadMediaRequest}
     */
    UploadMediaRequest,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
     * The WordMeaningDto model constructor.
     * @property {module:model/WordMeaningDto}
     */
    WordMeaningDto,

    /**
    * The ChatApi service constructor.
    * @property {module:api/ChatApi}
    */
    ChatApi,

    /**
    * The MessageApi service constructor.
    * @property {module:api/MessageApi}
    */
    MessageApi,

    /**
    * The SudokuControllerApi service constructor.
    * @property {module:api/SudokuControllerApi}
    */
    SudokuControllerApi,

    /**
    * The TicTacToeControllerApi service constructor.
    * @property {module:api/TicTacToeControllerApi}
    */
    TicTacToeControllerApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi,

    /**
    * The WordMeaningControllerApi service constructor.
    * @property {module:api/WordMeaningControllerApi}
    */
    WordMeaningControllerApi
};
